name: 'patreon post'
description: 'Publish patreon post'
inputs:
  login:
    description: 'patreon login'
    required: true
    default: ''
  password:
    description: 'patreon password'
    required: true
    default: ''
  body:
    description: 'post body'
    required: false
    default: ''

outputs:
  url: # id of output
    description: 'Post url'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.login }}
    - ${{ inputs.password }}
    - ${{ inputs.body }}